### ISSUE TITLE
Airspaces are not display anymore on mobiles

### ISSUE THREAD

**Issue by guillaumedc** [SpotAiR/SpotAiR#12]
**Describe the bug**
Airspaces are not display anymore on mobile.

**To Reproduce**
1. Activate airspaces
2. (optional) change settings to make sure to display something

**Expected behavior**
Airspaces should be display on map.
No airspace is drawn.

**Smartphone (please complete the following information):**
 - OS: Android 11
 - Browser: Firefox
 - Version: 103.1.0

**Comment by guillaumedc** [comment]
![Screenshot_20220804-161227_crDroid_Home](https://user-images.githubusercontent.com/1324781/182869258-a4a52e55-8992-453e-9956-e688279cf3c5.png)
![Screenshot_20220804-161241_crDroid_Home](https://user-images.githubusercontent.com/1324781/182869273-fc2451c4-0b70-40ec-9e02-b341b21b7028.png)

**Comment by SpotAiR** [comment]
Yes, bug already identified and fixed, but available for the next SpotAiR release (in a few days or weeks)

**Comment by SpotAiR** [comment]
Fixed with 2.3.2
