### ISSUE TITLE
Appli mobile

### ISSUE THREAD

**Issue by Synochy** [SpotAiR/SpotAiR#14]
Bonjour,

Bravo pour le travail effectué je suis un grand utilisateur de votre site web !
Est-ce qu'une application est prévue ? (même un simple embeded de la page web)

Par avance merci pour votre réponse.

**Comment by SpotAiR** [comment]
Bonjour,

Merci !

SpotAiR est PWA, une appli web. C'est à dire que sur les navigateurs compatibles (la plupart), vous pouvez utiliser SpotAiR "comme une appli native" : sans les barres de navigateur, dans sa propre fenêtre indépendante, ...
Dans le menu principal, si vous voyez l'item "Installer SpotAiR", c'est que votre navigateur est compatible, vous pouvez cliquer dessus.
Sinon, sur les autres navigateurs, utilisez leur fonction "Ajouter à l'écran d'accueil", et ce sera très similaire.

Donc, non, pas d'appli native prévue.  ;)

Salutations aériennes

**Comment by Synochy** [comment]
Bonjour,

merci beaucoup pour votre réponse.
J'ai changé de navigateur mobile (ça ne marchait pas sur Firefox nightly) et tout marche correctement.
