### ISSUE TITLE
Ajouter une balise piou piou

### ISSUE THREAD

**Issue by Bruno9555** [SpotAiR/SpotAiR#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bruno9555** [comment]
Peux-tu ajouter cette balise :

https://www.openwindmap.org/PP335

merci

**Comment by SpotAiR** [comment]
Elle y est déjà

**Comment by Bruno9555** [comment]
Ah oui merci excuse-moi… Par contre j'avais essayé d'installer les différentes webcam de l'Alpe d'Huez… Il n'y en a qu'une qui a été validé je t'envoie un lien vers les quatre autres : j'imagine que c'est plus facile à faire pour toi que pour moi ! 

https://www.oisans.com/decouvrir/domaines-skiables/les-webcams-en-oisans/webcams-de-lalpe-dhuez-grand-domaine-ski/

**Comment by SpotAiR** [comment]
Certaines sont hors ligne.
Je viens d'ajouter celle de Marmotte 3

**Comment by Bruno9555** [comment]
Merci !

**Comment by Bruno9555** [comment]
Coucou peux-tu ajouter les webcam des Deux-Alpes c'est vraiment un super si pour voler notamment en speed mais c'est assez cool de voir la météo des fonds de Vallée,

https://www.skaping.com/les2alpes/super-diable

Et sur cette page une toute une série qui permet de bien s'entendre de l'état du massif 😀 


https://www.skipass-2alpes.com/fr/webcams-les-deux-alpes

**Comment by Bruno9555** [comment]
Merci
