### ISSUE TITLE
Quid des balises Synop ?

### ISSUE THREAD

**Issue by lucguislain** [SpotAiR/SpotAiR#17]
Absence des balises synop depuis le 16 juillet 2023, version SpotAir 2.4.3.

![Screenshot_20230721-113544](https://github.com/SpotAiR/SpotAiR/assets/61451217/ca519b24-59aa-4300-b629-d7ab9a00a264)
![Screenshot_20230721-113502](https://github.com/SpotAiR/SpotAiR/assets/61451217/e4c148d8-1609-4aea-9a97-bab99b906487)

**Comment by SpotAiR** [comment]
Merci pour l'info, je n'avais pas vu.
Je regarde d'où vient le pb...

**Comment by SpotAiR** [comment]
Corrigé
