### ISSUE TITLE
Encodage des caractères - Spots FFVL

### ISSUE THREAD

**Issue by jimetevenard** [SpotAiR/SpotAiR#18]
Salut, la team Spotair !

**Describe the bug**
Sur les sites FFVL, l'encodage de caractères des données (accès, description, dangers...) n'est pas correct (cf. capture ci-jointe)

A vue de nez, on dirait de l'UTF-8 improprement interprété comme de l'ISO Latin  
(exemple : `dÃ©collage` au lieu de `décollage`)

Quand on clique sur le lien vers la fiche sport sur le site FFVL, on constate que l'encodage est le bon (UTF-8)

**To Reproduce**
1. Naviguer vers un spot dont la fiche FFVL comporte des accents  
    Exemple : SAINT MARC D'OUILLY https://www.spotair.mobi/spot/41752
2. Afficher les détails -> **l'encodage est cassé**
3. Cliquer sur le lien fiche spot [https://federation.ffvl.fr/](https://federation.ffvl.fr/sites_pratique/voir/101)
4. Sur le site FFVL, **l'encodage est bon.**

**Screenshots**
![screenshot](https://github.com/SpotAiR/SpotAiR/assets/23314625/14a6ae3a-fa0d-453b-bd9f-1aa3b54e979a)

**Desktop / Smartphone**
SpotAiR v2.4.3
Reproduit sur plusieurs navigateurs et OS différents (mobile ou desktop)

**Additional context**
*Remarque: Les fiches spots issues de Paragliding Earth ont le même souci d'encodage, mais là le problème semble être chez eux, car même sur leur site les encodages ne sont pas bons* ([exemple](https://www.paraglidingearth.com/?site=11362))

🪂  
Bon vols à tous,    
Bonne soirée !

**Comment by SpotAiR** [comment]
Hello
Oui, j'ai identifié le pb depuis quelques semaines. Ce sera corrigé début septembre.
Merci pour le signalement...
Salutations aériennes

**Comment by SpotAiR** [comment]
C'est corrigé
