### ISSUE TITLE
Bug : affichage graphiques BERA

### ISSUE THREAD

**Issue by lwznrx** [SpotAiR/SpotAiR#19]
**Describe the bug**
Lors de l'affichage des BERA, les graphiques ne chargent pas. En ouvrant les images dans un nouvel onglet, j'ai ce texte à la place : "expired token (16083)"

**To Reproduce**
1. Ouvrir un BERA dans un nouvel onglet sur PC ou smartphone

**Screenshots**
![image](https://github.com/SpotAiR/SpotAiR/assets/6987161/3d9fba70-9843-4d3b-8640-e135d5594d78)

**Navigateurs :**
 - PC : Firefox 119.0 (64 bits)
 - Smartphone : Chrome

**Comment by pmathieuffvlfr** [comment]
Merci pour l'info. J'y travaille....

**Comment by pmathieuffvlfr** [comment]
Ca sera bon pour les bulletins de demain (07/11)

**Comment by lwznrx** [comment]
Le problème est corrigé
