### ISSUE TITLE
«Add fav» dialog box is hidden when consulting a webcam

### ISSUE THREAD

**Issue by guillaumedc** [SpotAiR/SpotAiR#2]
**Dialog box to add a fav is not visible**
When trying to add a fav but webcam dialog box is open, the dialog box is opening beneath the current element.
Behavior is identical on smartphones and desktop.

**To Reproduce**
1. Open a webcam
2. Use **...** button to add an element of the list to fav
3. The fav dialog box is opened beneath the webcam dialog box

**Expected behavior**
Dialog box is displayed above webcam dialog box **or** webcam dialog box is closed

**Screenshots**
![spotair](https://user-images.githubusercontent.com/1324781/90105026-81e56d80-dd45-11ea-957d-aad72303d77d.png)

**Smartphone (please complete the following information):**
 - Device: LG G4
 - OS: Android 9
 - Browser: Firefox Beta
 - Version: 80.0.0-beta.4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 79.0

**Comment by SpotAiR** [comment]
Fixed.
Due for next release (1.3.9 or 2.0.0, don't know yet which one and when)
