### ISSUE TITLE
Données balises météo Holfuy

### ISSUE THREAD

**Issue by khhk** [SpotAiR/SpotAiR#20]
Connexion au données du réseau de balises météo Holfuy
https://holfuy.com/en/map/wind&la=46.73621&lo=3.13380&z=4.7

La page suivante donne plein de morceaux de code html pour l'intégration dans un autre site. J'imagine que la récupération des données que l'on veut afficher dans Spotair ne posera aucun souci à vos développeurs.
https://holfuy.com/en/widget

Je n'y connais quasiment rien en web. Si ça peut aider j'ai une station holfuy à 10min de chez moi à vélo, et des moyens de mesures que je peux déployer en doublon pour comparaison (station Vaisala WMT52).

**Comment by SpotAiR** [comment]
Bonsoir,
Je ne suis pas sûr de comprendre la motivation de ton message.
Les balises Holfuy (à quelques rares exceptions) sont présentes sur SpotAiR déjà depuis longtemps...
Quelle est le nom et la localisation de la balise Holfuy près de chez toi ? N'est-elle pas sur SpotAiR ?

Salutations aériennes
Pedro

**Comment by khhk** [comment]
Exemples de balises absentes :
- les 2 à proximité du site de Grenois (1187, 1484)
- celle près de chez moi sur le plateau de Saclay (1110)

**Comment by pedrom38** [comment]
OK, j'ai vérifié, ces 3 balises font partie du lot pour lesquelles les propriétaires n'ont PAS donné leur accord pour que les données soient diffusées ailleurs que sur le holfuy.com.

Si tu connais les propriétaires, tu peux aller les convaincre de donner leur accord !  ;)

**Comment by khhk** [comment]
Par quel moyen avez-vous demandé leur accord aux propriétaires des balises ?
Les propriétaires ont-ils tous reçu la demande ?
L'absence d'accord correspond-elle à une absence de réponse ou à une réponse négative ?
Le partenariat FFVL devrait garantir un accord pour au moins 1 des 3 balises que j'ai cité : elle appartient à un club.
Je vous tiens au courant.

**Comment by SpotAiR** [comment]
Je n'ai rien demandé.
C'est un procédé entre chaque propriétaire de balise et Holfuy lors de l'achat (je suppose).

Contactez le club en question, et soumettez leur le pb.

Vous pouvez aussi indiquer cette balise à balises@ffvl.fr
