### ISSUE TITLE
Balise disparue + lien netatmo

### ISSUE THREAD

**Issue by Bicycletterie** [SpotAiR/SpotAiR#21]
Salut et bravo pour l'appli géniale.
Cette balise n'apparait plus sur spotair : 
https://weathermap.netatmo.com/?zoom=10&type=wind&lat=44.503732343935496&lng=1.8755722045898438&lang=fr

Merci !!

**Comment by SpotAiR** [comment]
Bonjour,
Pour être sûr : de quelle balise s'agit-il ?
Un nom ? Mieux : un ID ?
Merci

**Comment by Bicycletterie** [comment]
Deco du saut de la Mounine.
Piou piou 176

8 janv. 2024 15:13:04 SpotAiR ***@***.***>:

**Comment by SpotAiR** [comment]
Euuuh. C'est une Netatmo ou une Pioupiou ? Je ne comprends pas...

**Comment by SpotAiR** [comment]
Si c'est la Pioupiou 176 : elle est marquée comme "en maintenance" dans les données fédérales.
Et elle est appelée "Montbrun" toujours dans ces données fédérales.
Je tinvite donc à faire un mail à balises [chez] ffvl.fr en indiquant le maximum de données : nom, position gps, observations aérologiques, ....
Et le mieux serait que ce soit le gestionnaire (club "Causses en Ailes" ?) qui le fasse. Si tu en es et/ou que tu les connais, je tinvite à te rapprocher d'eux
Merci
