### ISSUE TITLE
Appli mobile TWA

### ISSUE THREAD

**Issue by jul-o** [SpotAiR/SpotAiR#22]
Bonjour, j'ai vu [cette issue](https://github.com/SpotAiR/SpotAiR/issues/14) dans laquelle vous faites part de votre décision de ne pas développer SpotAir en native. Je comprends tout à fait la décision, étant donné le volume de développement supplémentaire requis, alors que le site fonctionne très bien en PWA. Cependant, je pense que la majorité des utilisateurs ne savent pas qu'il est possible d'"installer" certains sites web, d'où la pertinence - en mon sens - d'avoir une appli sur les stores.
Avez-vous pensé à faire une [TWA](https://developer.chrome.com/docs/android/trusted-web-activity) ? Ça permettrait de bundler la PWA en apk, et donc de l'avoir sur le play store (en plus d'avoir un meilleur accès aux APIs native, telles que les notifications push, si jamais ça s'avère utile un jour). L'avantage est d'avoir des applis très peu différenciables d'applis natives, qui s'installent de la même manière, et qui ne requièrent pas ou peu de développement supplémentaire (juste de la config, et un ajout à la pipeline de déploiement).
Par ailleurs, je sais qu'il y a des équivalents pour l'app store, mais je suis moins renseigné.

Si cette issue ne semble pas pertinente, n'hésitez pas à l'archiver. Merci pour votre travail !

**Comment by SpotAiR** [comment]
Bonjour,
Il n'est pas impossible que cela change cette année et qu'une application native soit développée (également sur iPhone) à base de WebView. Pour répondre à des besoins très spécifiques auquels les PWA et TWA ne peuvent pas répondre.
Mais ce n'est pas encore tranché...
Wait and see  ;)

**Comment by AlexFly74** [comment]
Bonjour, Je ne suis pas informaticien et ne comprends pas le messages précédent mais peut être, est il une partie de la réponse que j'attendais. Comme pas mal de parapentiste, j'utilise mon téléphone avec une apli pour voler. Pour ma part c'est un iPhone FlySkyHy) et j'utilise pas mal l'assistant vocal Siri pour ouvrir des apps en l'air (Zello, envoyer un message WhatsApp, voir téléphoner, lancer Flyskyhy, l'appareil photo, ...). cela évite de lâcher les commandes et de passer d'une app à l'autre. Malheureusement ce n'est pas possible avec SpotAir qui n'a pas l'air d'être considéré comme une application. Est il possible d'arranger cela ? Merci

**Comment by SpotAiR** [comment]
> Bonjour, Je ne suis pas informaticien et ne comprends pas le messages précédent mais peut être, est il une partie de la réponse que j'attendais. Comme pas mal de parapentiste, j'utilise mon téléphone avec une apli pour voler. Pour ma part c'est un iPhone FlySkyHy) et j'utilise pas mal l'assistant vocal Siri pour ouvrir des apps en l'air (Zello, envoyer un message WhatsApp, voir téléphoner, lancer Flyskyhy, l'appareil photo, ...). cela évite de lâcher les commandes et de passer d'une app à l'autre. Malheureusement ce n'est pas possible avec SpotAir qui n'a pas l'air d'être considéré comme une application. Est il possible d'arranger cela ? Merci

Pas de neuf sur le sujet. SpotAiR reste une appli web.
