### ISSUE TITLE
couleurs 

### ISSUE THREAD

**Issue by guillaumeportails** [SpotAiR/SpotAiR#23]
Dans les fiches site, la couleur "genre de bleu" pour le texte sur le fond de couleur "genre de vert" me rend la lecture impossible.

Mon téléphone est en night-mode (préférence texte blanc sur fond noir), mieux pour la batterie en AMOLED.

Cf fiche Beynes (78)
![Screenshot_20240127_101057_Firefox](https://github.com/SpotAiR/SpotAiR/assets/10489735/0866d7ef-1c77-4693-8bbb-21fc4603d450)

**Comment by SpotAiR** [comment]
Bonjour,
Excusez moi pour le délai de réponse, j'avais zappé votre "issue".
Ben là, je ne peux que constater que votre téléphone modifie sensiblement les couleurs définies dans SpotAiR. Un mode spécifique du système ? Du navigateur ? A vous de voir...

Pour preuve la même fenêtre sans trafic : cf pièce jointe. Tout y est lisible je pense.
![www spotair mobi_(Samsung Galaxy S8+) (6)](https://github.com/SpotAiR/SpotAiR/assets/65925625/7146cabe-58d9-4036-aad1-f333fdcca61d)

Salutations aériennes

Pedro
