### ISSUE TITLE
accès au détail d'une balise pour le vent

### ISSUE THREAD

**Issue by jpliotier** [SpotAiR/SpotAiR#24]
bonjour,
le lien : https://www.spotair.mobi/page/wind/pioupiou/977 ne fonctionne plus.
depuis le widget : 
<iframe width="75" height="75" frameBorder="0" src="https://www.spotair.mobi/widget/wind/pioupiou/977?mode=free_flight&unit=kmh&name=false&quadrant=false&windValues=true&dark=true"></iframe>

lorsque l'on clique sur l'image, le detail n'apparait plus.

y a t'il une solution envisagée ?
cordialemùent

**Comment by SpotAiR** [comment]
Merci pour l'info ! Bug corrigé
