### ISSUE TITLE
Enregistrement avec une adresse mail invalide

### ISSUE THREAD

**Issue by pierre-quelin** [SpotAiR/SpotAiR#25]
Bonjour,

j'ai voulu m'enregistrer sur le site mais j'ai fait une faute de frappe sur mon adresse mail. L'adresse saisie est invalide.
Après quelques jours, il m'est toujours interdit d'utiliser le même pseudo car celui-ci reste réservé et associé à cette adresse invalide.

Comment procéder pour le supprimer ?

Merci

**Comment by SpotAiR** [comment]
Bonjour,
Après ton erreur, comment SpotAiR pourrait vérifier que tu es bien la même personne qui revendique ce pseudo ?
Sans mail impossible automatiquement...

Contacte moi par mail, on trouvera une solution.

Pierre

**Comment by pierre-quelin** [comment]
Bonjour,

à minima il faudrait vérifier les adresses mail et retirer les comptes avec des adresses invalides.

Merci

Pierre

**Comment by SpotAiR** [comment]
Si tu m'expliques comment vérifier ***simplement*** une adresse mail, je veux bien.  ;)

**Comment by pierre-quelin** [comment]
Bonjour,
je n'ai pas de solution miracle effectivement. Voici quelques solutions que j'imagine.
La suppression des comptes non validés au bout d'un certain laps de temps peut-être une 1ère solution.
L'envoi periodique de mails de confirmation peut-être une autre solution pour supprimer les comptes qui ne sont plus utilisés.
Plus compliqué, l'envoi d'un mail sur une adresse invalide est généralement suivie d'une réponse du serveur de type "delivery status".
Après je comprends que ce n'est peut être pas la priorité du moment.
En tout cas merci
Pierre
