### ISSUE TITLE
Landing and takeoff are not displayed if both are selected

### ISSUE THREAD

**Issue by AurelienS** [SpotAiR/SpotAiR#27]
**Describe the bug**
In the filter section, if you select both options "Takeoff" and "Landing", both are hidden.
If you select either one, the selected one is correctly displayed.

**To Reproduce**
open the filter pan, select both Takeoff and Landing

**Expected behavior**
Both Landing and Takeoff should appear

**Screenshots**
![image](https://github.com/SpotAiR/SpotAiR/assets/7090390/371a0676-20fe-427d-bca6-cde182c51ab3)
![image](https://github.com/SpotAiR/SpotAiR/assets/7090390/61680a48-8608-4392-8978-043e367f5d7f)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 124.0.6367.119 (Official Build) (64-bit)

**Comment by SpotAiR** [comment]
Hello
Yes, when you check "Landing" and "Takeoff" filters, only spots that are used as takeoff AND landing are displayed. Typically winch spots or top landing spots.
Regards
