### ISSUE TITLE
Add "balise du Revard"

### ISSUE THREAD

**Issue by abdomit** [SpotAiR/SpotAiR#3]
There is a new way to retrieve data from "balise du Revard" (in Savoy, near Aix-les-bain). 

Currently there are 2 wind sensors: a Pioupiou (# 159) and EuclideSystems (from 1991). The Pioupiou will possibly be removed in the futur, this is why it would be nice to include the EuclideSystems in SpotAiR.

The values given by this sensor can be access on this [website](http://balisesmet.chez.com/). There is a [JSON file](http://balisesmet.chez.com/BaliseRevard/balise_live.json) available to easily get RAW data.

Unfortunately there is currently no other way to get the measured value from this sensor (to my knowledge), it would be extremely useful for local pilots to have access to this sensor with StopAiR.

Thanks for your work on StopAiR

**Comment by SpotAiR** [comment]
Yes. I talked with the guy who owns the stations and publish the data.
Work in progress...

**Comment by abdomit** [comment]
Great news!

**Comment by SpotAiR** [comment]
Done. Online.
