### ISSUE TITLE
Amélioration du "hike and fly"

### ISSUE THREAD

**Issue by lwznrx** [SpotAiR/SpotAiR#7]
Amélioration : rajouter un mode parallèle au "hike and fly".

Au lieu d'afficher des couleurs donner l'altitude sol, afficher des couleurs donnant la finesse nécessaire pour atteindre ce point. On aurait donc une finesse infinie pour tous les points à la même altitude, et nulle par exemple au pied d'une falaise, avec le point de départ en haut de la falaise.

Avec une autre amélioration possible : choisir l'altitude de départ (en absolu ou relatif) dans le menu permettant actuellement d'entrer la finesse de son aile, ce qui permettrait simplement de calculer ses transitions, selon les plafs, en haut des pompes.

Et tant que j'y suis, je pose ça ici (est-ce mieux d'ouvrir une nouvelle issue ?), bon déjà le mode hike&fly n'a pas marché pour moi pendant un moment, il remarche aujourd'hui, je ne sais pas pourquoi. Si j'ai de nouveau le problème je ferai une issue plus claire. 

Mais surtout, il serait intéressant que sur un nouveau clic, au lieu de ne rien faire si on est dans une zone en couleur (où on a la finesse d'aller donc), et de recalculer en dehors de cette zone, soit réinitialiser le mode, soit relancer le calcul forcément. Car pour calculer depuis un point à l'intérieur de cette zone, on est obligés de calculer une zone où le futur point sera gris, pour recalculer (car annuler / relancer le mode hike&fly garde en mémoire l'ancien point). 
Exemple : 
![image](https://user-images.githubusercontent.com/6987161/107980770-1fee1500-6fc1-11eb-8344-7fa1cc4a3e16.png)
Ok c'est bon du plateau des Pavis, voyons du col de Bise... Ah non pas possible. Donc obligé de faire quelque chose comme ça : 
![image](https://user-images.githubusercontent.com/6987161/107980870-4c099600-6fc1-11eb-96ba-f6788e95759c.png)
Puis col de Bise :
![image](https://user-images.githubusercontent.com/6987161/107980895-57f55800-6fc1-11eb-8b08-f629aeabd75b.png)

**Comment by SpotAiR** [comment]
Pour ce qui est du pb "ca marche / ca marche pas / ca marche", effectivement j'ai détecté des dysfonctionnements, mais je ne m'explique pas d'où ils peuvent venir, puisque je ne les reproduis pas sur mes autres plateformes de travail. Investigation en cours.

Pour les idées d'améliorations :
- couleur variant selon la finesse nécessaire. Bof, pas sûr de l'intérêt.
- choix de l'altitude de départ : oui je prends (d'ailleurs c'est possible sur hikeandfly.org mais je ne l'ai pas repris dans un premier temps pour simplifier)
- moyen de relancer un calcul par clic ou autre : ok, oui, faut améliorer ça. A voir ce qui est le plus intelligent : clic, double-clic, clic-droit, ... sur la carte, sur le bouton de l'outil, .... on peut imaginer beaucoup de choses.... à voir

**Comment by lwznrx** [comment]
Merci de la réponse (et de la nouvelle version tant qu'on y est !)

Concernant ton 3e point : double clic peu pertinent, pour un usage mobile, idem clic droit. Un niveau clic qui relance le calcul peu importe où il soit fait me semblerait adapté. Et supprimer les donnés du calcul en cache lors de l'arrêt du mode hike&fly. 

Que penses-tu d'une fusion des 2 mddes sinon ? Le 1er clic lance le mode hike&fly comme actuellement, le clic suivant lance le calcul de l'autre mode. Dans une optique de simplifier et épurer le truc.

**Comment by SpotAiR** [comment]
J'ai opté pour le fonctionnement suivant :
- je garde en mémoire le calcul lorsque désactive puis réactive H&F (rien changé là dessus)
- tout clic sur la carte relance le calcul, même un clic dans une zone en couleur

Ce sera effectif sur la prochaine release (je ne sais pas quand, désolé !)
