### ISSUE TITLE
Balise OCA - Calern

### ISSUE THREAD

**Issue by jbrun3t** [SpotAiR/SpotAiR#8]
Bonjour,

Serait-il possible d'ajouter la balise de l'observatoire de la cote d'azur (OCA - Calern):
https://ocatools.oca.eu/calern/meteo/client.htm

Comme vous pouvez le voir, la présentation est pas terrible mais sûrement pas très compliquer a parser.
L'info en elle même est intéressante en terme de securite. Cette balise est bien expose, y compris en tendance Nord et Ouest. La balise de l'embarnier est (dans une certaine mesure) abritee de ces tendances , potentiellement dangereuse sur le site  de vol libre de Gourdon.

Si on pouvait rendre l'info de la balise de l'OCA accessible facilement, cela pourrait contribuer a ameliorer la securite dans cette zone. Évidemment, je suis pret a aider :)  

Cela vous parait il possible ?

**Comment by SpotAiR** [comment]
Bonjour,

Oui ça a l'air facile à parser. Ça se ferait sans problème d'un point de vue technique.

Mais il y a 2 points qui -en l'état- freinent ce genre d'intégration :
- je cherche l'accord des propriétaires des données en premier lieu. Et ce contact peut aussi permettre d'avoir accès aux données brutes (API, base de données, ...).
- maintenir de nombreux bouts de code de parsing spécifiques deviendrait vite infernal, donc à priori je ne fais pas.

Je vous propose les étapes suivantes :
1) prendre contact avec l'OCA pour obtenir leur accord
2a) si accord AVEC accès aux données brutes : intégration dans SpotAiR par mes soins
2b) si accord SANS accès aux données brutes : vous développez le script de parsing, et vous pouvez utiliser l'API de SpotAiR (https://www.spotair.mobi/help/api.php#releve_put) pour pousser les relevés

Qu'en pensez-vous ?

Si vous pouvez vous charger de les contacter, ce serait parfait  ;)

**Comment by jbrun3t** [comment]
> Bonjour,
> 
> Oui ça a l'air facile à parser. Ça se ferait sans problème d'un point de vue technique.
> 
> Mais il y a 2 points qui -en l'état- freinent ce genre d'intégration :
> 
>     * je cherche l'accord des propriétaires des données en premier lieu. Et ce contact peut aussi permettre d'avoir accès aux données brutes (API, base de données, ...).
> 
>     * maintenir de nombreux bouts de code de parsing spécifiques deviendrait vite infernal, donc à priori je ne fais pas.

Je comprend

> 
> 
> Je vous propose les étapes suivantes :
> 
>     1. prendre contact avec l'OCA pour obtenir leur accord
>        2a) si accord AVEC accès aux données brutes : intégration dans SpotAiR par mes soins
>        2b) si accord SANS accès aux données brutes : vous développez le script de parsing, et vous pouvez utiliser l'API de SpotAiR (https://www.spotair.mobi/help/api.php#releve_put) pour pousser les relevés
> 
> 
> Qu'en pensez-vous ?

Top

> 
> Si vous pouvez vous charger de les contacter, ce serait parfait ;)

Je vais essayer de les contacter

**Comment by SpotAiR** [comment]
Salut, 

  Excusez moi pour le temps de réponse. 

  Je rechigne à faire des développements pour 1 seule balise. Mais par
contre, si vous avez le courage de développer un traitement régulier
(toutes les 10 mins ?) qui parse cette page et envoie les résultats à
SpotAiR. Ca peut être une solution. 

  https://www.spotair.mobi/help/api.php#releve_put 

  Salutations aériennes 

  Pedro 

Le 17/02/2021 22:02, Jerome Brunet a écrit :

> Bonjour, 
> 
> Serait-il possible d'ajouter la balise de l'observatoire de la cote d'azur (OCA - Calern):
> https://ocatools.oca.eu/calern/meteo/client.htm 
> 
> Comme vous pouvez le voir, la présentation est pas terrible mais sûrement pas très compliquer a parser.
> L'info en elle même est intéressante en terme de securite. Cette balise est bien expose, y compris en tendance Nord et Ouest. La balise de l'embarnier est (dans une certaine mesure) abritee de ces tendances , potentiellement dangereuse sur le site de vol libre de Gourdon. 
> 
> Si on pouvait rendre l'info de la balise de l'OCA accessible facilement, cela pourrait contribuer a ameliorer la securite dans cette zone. Évidemment, je suis pret a aider :) 
> 
> Cela vous parait il possible ? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1] https://github.com/SpotAiR/SpotAiR/issues/8
[2]

**Comment by aloysb** [comment]
Si seulement c'était de l'Open Source, on aurait pu amener sa pierre à l'édifice 😊

En tout cas, bon boulot. Bonne continuation 💪
