### ISSUE TITLE
Users cannot fix broken webcam metadata when image url is invalid

### ISSUE THREAD

**Issue by julpil** [SpotAiR/SpotAiR#9]
**Is your feature request related to a problem? Please describe.**
Users cannot fix broken webcam metadata when image url is invalid. 

Example: Webcam in Champsaur, such as Laye. Current image url: https://www.champsaur3gliss.com/webcam/laye/camera.jpg. Actual image url: http://www.trinum.com/ibox/ftpcam/mega_laye_front-de-neige.jpg

This webcam cannot be fixed using "Suggest changes for this webcam" feature because it is not displayed on the map (on https://webcams.spotair.mobi/). Toggling "offline" or "freezed" webcams filters doesn't help since the webcam remains hidden.

**Describe the solution you'd like**
Allow users to modify webcam metadata when image url is invalid. Optionally show webcams with broken image url on the map.

**Describe alternatives you've considered**
- Contact SpotAiR admin for each webcam. This doesn't seem scalable.
- Rely on webcam maintainers to redirect correctly. No guarantees.
- Submitting a duplicate webcam to fix the issue. This is discouraged (_"
Merci de veiller à ne pas créer de doublon (même d'une webcam en cours de validation ou invalidée)."_)
- Directly hit https://webcams.spotair.mobi/page_submit.php?ref=webcam-id but this requires to know the webcam id first.

**Comment by SpotAiR** [comment]
In this case, you can create a duplicate. Because I think that the new one is not at the same place as the old/bad one.
